<script>
    import { fade, fly } from "svelte/transition";
    import { Button } from "$lib/components/ui/button";
    import * as Card from "$lib/components/ui/card";

    export let activeAnalysis;
    export let loadingAnalysis;
    export let loadingStatus;
    export let onClose;
</script>

<!-- svelte-ignore a11y-click-events-have-key-events, a11y-no-static-element-interactions -->

<!-- svelte-ignore a11y-click-events-have-key-events, a11y-no-static-element-interactions -->
<div
    class="fixed inset-0 bg-background/80 backdrop-blur-sm flex items-center justify-center p-4 z-50"
    onclick={onClose}
    transition:fade={{ duration: 200 }}
>
    <!-- svelte-ignore a11y-click-events-have-key-events, a11y-no-static-element-interactions -->
    <div
        class="w-full max-w-5xl max-h-[90vh] flex flex-col"
        onclick={(e) => e.stopPropagation()}
        transition:fly={{ y: 20, duration: 300 }}
    >
        <Card.Root
            class="h-full shadow-2xl border-primary/20 flex flex-col overflow-hidden"
        >
            {#if loadingAnalysis}
                <div class="flex flex-col items-center justify-center h-96 p-8">
                    <div class="relative w-16 h-16 mb-6">
                        <div
                            class="absolute inset-0 rounded-full border-b-2 border-primary animate-spin"
                        ></div>
                    </div>
                    <p class="text-lg font-medium animate-pulse">
                        {loadingStatus}
                    </p>
                </div>
            {:else}
                <Card.Header
                    class="border-b bg-muted/20 flex flex-row items-center justify-between sticky top-0 z-10 shrink-0"
                >
                    <div>
                        <Card.Title class="text-2xl flex items-center gap-2">
                            {activeAnalysis.ticker}
                            <span class="text-muted-foreground font-normal"
                                >/</span
                            >
                            {activeAnalysis.title || activeAnalysis.form}
                        </Card.Title>
                        <Card.Description class=""
                            >Generated by Gemini 3 Flash Preview</Card.Description
                        >
                    </div>
                    <Button
                        variant="ghost"
                        size="icon"
                        class=""
                        disabled={false}
                        onclick={onClose}
                    >
                        <span class="h-4 w-4">✕</span>
                    </Button>
                </Card.Header>
                <Card.Content
                    class="overflow-y-auto p-8 custom-scrollbar flex-1 overscroll-contain"
                >
                    <div class="prose prose-invert prose-slate max-w-none">
                        {@html activeAnalysis.content
                            .replace(
                                /^# (.*$)/gim,
                                '<h1 class="text-3xl font-bold mb-6 pb-2 border-b">$1</h1>',
                            )
                            .replace(
                                /^## (.*$)/gim,
                                '<h2 class="text-xl font-bold text-primary mt-8 mb-4">$1</h2>',
                            )
                            .replace(
                                /^### (.*$)/gim,
                                '<h3 class="text-lg font-semibold mt-6 mb-2">$1</h3>',
                            )
                            .replace(
                                /\*\*(.*?)\*\*/g,
                                '<strong class="font-bold text-foreground">$1</strong>',
                            )
                            .replace(
                                /^\- (.*$)/gim,
                                '<li class="ml-4 list-disc mb-1">$1</li>',
                            )
                            .replace(/\n/g, "<br/>")}
                    </div>
                </Card.Content>
            {/if}
        </Card.Root>
    </div>
</div>

<style>
    /* Custom Scrollbar */
    :global(.custom-scrollbar::-webkit-scrollbar) {
        width: 6px;
    }
    :global(.custom-scrollbar::-webkit-scrollbar-track) {
        background: transparent;
    }
    :global(.custom-scrollbar::-webkit-scrollbar-thumb) {
        background: hsl(var(--muted-foreground) / 0.3);
        border-radius: 4px;
    }
    :global(.custom-scrollbar::-webkit-scrollbar-thumb:hover) {
        background: hsl(var(--muted-foreground) / 0.5);
    }
</style>
